-- MySQL Script generated by MySQL Workbench
-- Mon Feb 10 23:18:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `carne` INT NOT NULL AUTO_INCREMENT,
  `dpi` BIGINT(20) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `fecha_nac` DATETIME NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  PRIMARY KEY (`carne`),
  UNIQUE INDEX `dpi_UNIQUE` (`dpi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_cuenta` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuenta` (
  `id` INT NOT NULL,
  `no_cuenta` BIGINT(20) NOT NULL,
  `tipo_cuenta_id` INT NOT NULL,
  `Usuario_carne` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `no_cuenta_UNIQUE` (`no_cuenta` ASC),
  INDEX `fk_cuenta_tipo_cuenta_idx` (`tipo_cuenta_id` ASC),
  INDEX `fk_cuenta_Usuario1_idx` (`Usuario_carne` ASC),
  CONSTRAINT `fk_cuenta_tipo_cuenta`
    FOREIGN KEY (`tipo_cuenta_id`)
    REFERENCES `mydb`.`tipo_cuenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_Usuario1`
    FOREIGN KEY (`Usuario_carne`)
    REFERENCES `mydb`.`Usuario` (`carne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
